source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

def common
  pod 'RxSwift', '>= 6.0.0-rc.1'
  pod 'RxCocoa', '>= 6.0.0-rc.1'
  pod 'RealmSwift'
end

target 'RxRealm_Example' do
  platform :ios, '9.0'
  common
  pod 'RxRealm', :path => '../'
end

target 'RxRealm_Tests' do
  platform :ios, '9.0'
  common
  pod 'RxBlocking', '>= 6.0.0-rc.1'
  pod 'RxRealm', :path => '../'
end
